# Generated by Django 3.2.13 on 2022-05-13 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo')),
                ('is_recolector', models.BooleanField(default=False, verbose_name='Recolector')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('cedula', models.IntegerField(verbose_name='Cedula')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('fecha', models.DateTimeField(verbose_name='FechaNacimiento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Despulpado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(verbose_name='FechaInicial')),
                ('fechaFinal', models.DateTimeField(verbose_name='FechaFinal')),
                ('cantidadCafe', models.FloatField(verbose_name='CantidadCafe')),
                ('cantidadMucilago', models.FloatField(verbose_name='CantidadMucilago')),
                ('cantidadAgua', models.FloatField(verbose_name='CantidadAgua')),
            ],
        ),
        migrations.CreateModel(
            name='Fermentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(verbose_name='FechaInicial')),
                ('fechaFinal', models.DateTimeField(verbose_name='FechaFinal')),
                ('cantidadEntra', models.FloatField(verbose_name='CantidadEntra')),
                ('cantidadSale', models.FloatField(verbose_name='CantidadSale')),
                ('tempAmb', models.FloatField(verbose_name='TemperaturaAmbiente')),
                ('tempGrano', models.FloatField(verbose_name='TemperaturaGrano')),
                ('brix', models.FloatField(verbose_name='Brix')),
                ('ph', models.FloatField(verbose_name='pH')),
                ('cantidadAgua', models.FloatField(verbose_name='CantidadAgua')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicacion')),
                ('altitud', models.FloatField(verbose_name='Altitud')),
                ('clima', models.CharField(max_length=30, verbose_name='Clima')),
                ('inclinacion', models.FloatField(verbose_name='Inclinacion')),
                ('lumenes', models.FloatField(verbose_name='Lumenes')),
                ('coordenadas', models.CharField(max_length=50, verbose_name='Coordenadas')),
                ('tierra', models.CharField(max_length=40, verbose_name='Tierra')),
                ('ph', models.FloatField(verbose_name='pH')),
                ('cultivos', models.CharField(max_length=500, verbose_name='Cultivos')),
                ('microorganismos', models.CharField(max_length=500, verbose_name='Microorganismos')),
            ],
        ),
        migrations.CreateModel(
            name='Lavado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(verbose_name='FechaInicial')),
                ('fechaFinal', models.DateTimeField(verbose_name='FechaFinal')),
                ('cantidadEntra', models.FloatField(verbose_name='CantidadEntra')),
                ('cantidadSale', models.FloatField(verbose_name='CantidadSale')),
                ('cantidadAgua', models.FloatField(verbose_name='CantidadAgua')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, verbose_name='Cantidad')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lote', to='authApp.finca')),
            ],
        ),
        migrations.CreateModel(
            name='Tostion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('cantidadEntra', models.FloatField(verbose_name='CantidadEntra')),
                ('cantidadSale', models.FloatField(verbose_name='CantidadSale')),
                ('temp1', models.FloatField(verbose_name='TemperaturaCrack1')),
                ('temp2', models.FloatField(verbose_name='TemperaturaCrack2')),
                ('temp3', models.FloatField(verbose_name='TemperaturaCrack3')),
                ('tiempo1', models.FloatField(verbose_name='TiempoCrack1')),
                ('tiempo2', models.FloatField(verbose_name='TiempoCrack2')),
                ('tiempo3', models.FloatField(verbose_name='TiempoCrack3')),
                ('tempPromedio', models.FloatField(verbose_name='TemperaturaPromedio')),
                ('tiempoPromedio', models.FloatField(verbose_name='TiempoPromedio')),
                ('aromas', models.CharField(max_length=500, verbose_name='Aromas')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('lote', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tostion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('distancia', models.FloatField(verbose_name='Distancia')),
                ('profundidad', models.FloatField(verbose_name='Profundidad')),
                ('inclinacion', models.FloatField(verbose_name='Inclinacion')),
                ('semilla', models.CharField(max_length=50, verbose_name='Semilla')),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Siembra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('cantidadEntra', models.FloatField(verbose_name='CantidadEntra')),
                ('cantidadSale', models.FloatField(verbose_name='CantidadSale')),
                ('defectuosos', models.FloatField(verbose_name='Defectuosos')),
                ('lote', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seleccion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Secado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(verbose_name='FechaInicial')),
                ('fechaFinal', models.DateTimeField(verbose_name='FechaFinal')),
                ('tempAmb', models.FloatField(verbose_name='TemperaturaAmbiente')),
                ('tempGrano', models.FloatField(verbose_name='TemperaturaGrano')),
                ('humedad', models.FloatField(verbose_name='Humedad')),
                ('densidad', models.FloatField(verbose_name='Densidad')),
                ('lote', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Secado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('agua', models.FloatField(verbose_name='Agua')),
                ('lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Riego', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Poda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Molienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('cantidadEntra', models.FloatField(verbose_name='CantidadEntra')),
                ('cantidadSale', models.FloatField(verbose_name='CantidadSale')),
                ('lote', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Molienda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('despulpado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.despulpado')),
                ('fermentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.fermentacion')),
                ('lavado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.lavado')),
                ('molienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.molienda')),
                ('secado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.secado')),
                ('tostion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.tostion')),
            ],
        ),
        migrations.AddField(
            model_name='lavado',
            name='lote',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote'),
        ),
        migrations.AddField(
            model_name='lavado',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lavado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Fertilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.FloatField(verbose_name='Relacion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fertilizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fermentacion',
            name='lote',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote'),
        ),
        migrations.AddField(
            model_name='fermentacion',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fermentacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='despulpado',
            name='lote',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote'),
        ),
        migrations.AddField(
            model_name='despulpado',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Despulpado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('cantidad', models.FloatField(verbose_name='Masa')),
                ('defectos', models.FloatField(verbose_name='Defectos')),
                ('lote', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cosecha', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Catacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('tiempo1', models.FloatField(verbose_name='Tiempo1')),
                ('tiempo2', models.FloatField(verbose_name='Tiempo2')),
                ('tiempo3', models.FloatField(verbose_name='Tiempo3')),
                ('puntaje', models.FloatField(verbose_name='Puntaje')),
                ('lote', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.lote')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='CAtacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Finca', to='authApp.finca'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
