# Generated by Django 4.0.4 on 2022-05-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=30, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(max_length=30, verbose_name='Celular'),
        ),
    ]
